### ISSUE TITLE
Cannot use for domain that uses ALIAS record

### ISSUE THREAD

**Issue by glward** [infinityofspace/certbot_dns_porkbun#67]
**Describe the bug**
Attempting to update/renew certificate on a domain that uses an ALIAS record fails, because it attempts to update the resolved ALIAS domain instead of the domain requested

**To Reproduce**
1. Set an ALIAS record for a root domain, instead of an A/AAAA record
2. Attempt to create/renew certificate for that domain 

**Expected behavior**
Certificate renewal is successful 

**Certbot command**
certbot  certonly -v --test-cert --server https://acme-staging-v02.api.letsencrypt.org/directory --authenticator dns-porkbun            --dns-porkbun-credentials /etc/letsencrypt/porkbun/porkbun.ini --cert-name test-d example.com

**Versions (please complete the following version information):**
 - certbot: 2.4.0
 - certbot_dns_porkbun: 0.8

**Error message**
```
2024-01-01 15:29:04,837:DEBUG:urllib3.connectionpool:https://porkbun.com:443 "POST /api/json/v3/dns/create/dyndns.org HTTP/1.1" 400 None
2024-01-01 15:29:04,843:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/certbot_dns_porkbun/cert/client.py", line 109, in _perform
    self.record_ids[validation] = self._get_porkbun_client().dns_create(self._root_domain,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pkb_client/client.py", line 119, in dns_create
    raise Exception("ERROR: DNS create api call was not successfully\n"
Exception: ERROR: DNS create api call was not successfully
Status code: 400
Message: Invalid domain.
```

Note trying to request a cert for "dyndns.org" (the root of the domain that my domain is pointing at with an ALIAS record) and not my domain

**Comment by infinityofspace** [comment]
Thank you for your bug report.

ANAME/ALIAS records are treated like CNAME and DNAME records according to the specification of the DNS-01 challenge, i.e. the DNS-01 challenge domain `_acme-challenge.<fqdn>` is resolved and then the challenge value is set for this resolved domain.

For example, the following DNS records are equivalent in this context:

```
_acme-challenge.mydomain.com. 600 IN ALIAS _acme-challenge.example.com.
_acme-challenge.mydomain.com. 600 IN CNAME _acme-challenge.example.com.
```
The failed attempts as you describe should only occur if you use a wildcard `ALIAS` entry.
However, I cannot complete the debugging with your current information, so I would ask you to provide the exact DNS constellation. You can mask the domain names, but you should keep the number of subdomains.

For this reason, the following possible solutions are only general and may not apply depending on the DNS constellation.

## Solutions:

### Modify DNS ALIAS record

So if you use a DNS record like this one:
```
*.mydomain.com. 600 IN ALIAS example.com.
```
You have to adjust it and remove the wildcard. Because every request for the challenge `_acme-challenge.mydomain.com.` is forwarded to `_acme-challenge.example.com`. As you have specified this with the `ALIAS` record.

### Forward challenge to other controlled domain

You can also create a DNS record that points to a domain/subdomain that does not forward and is a Porkbun domain that you control.

For example:
```
_acme-challenge.mydomain.com. 600 IN CNAME mydomain2.com.
```

### Create a dummy A record

The domain for the challenge is resolved according to the DNS-01 specification, so you can also create a dummy DNS `A` record. In this case, the existing DNS `ALIAS` wildcard record would be retained and the DNS-01 challenge would still be performed successfully.

For example:
```
*.mydomain.com. 600 IN ALIAS _acme-challenge.example.com.
_acme-challenge.mydomain.com. 600 IN A 0.0.0.0
```

**Comment by glward** [comment]
The dummy A record seems like a reasonable option, I'll give that a try. Note that this same setup worked fine with my previous registrar (gandi) and the plugin I was using for them.

The full DNS records for the domain are:

```
@ 600 IN ALIAS mydomain.dyndns.org
*.mydomain.io. 600 IN ALIAS mydomain.dyndns.org
@ 600 IN MX 10 fwd1.porkbun.com
@ 600 IN MX 20 fwd2.porkbun.com
@ 300 IN TXT <SPF config>
default._domainkey.mydomain.io 300 IN TXT <DKIM config>
_dmarc.mydomain.io 300 IN TXT <DMARC config>
```

I've updated the wildcard to be a CNAME pointing at my root, though at the back of my mind I feel like that causes other issues when the root is an ALIAS. I'll try that once it propagates and, if that fails, I'll try the dummy A record for `_acme-challenge`. Thanks!

**Comment by glward** [comment]
Using a dummy A record works fine. Thanks again for the help!
